[wokwi]
version = 1
elf = ".pio/build/esp32AIThinker_sim/OpenIris-v1.10.6-esp32AIThinker_sim-c0391d0-feature-improv.elf"
firmware = ".pio/build/esp32AIThinker_sim/OpenIris-v1.10.6-esp32AIThinker_sim-c0391d0-feature-improv.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
